# Generated by Django 5.1.6 on 2025-02-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
    ]
